server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  jsp-servlet:
    init-parameters:
      development: true

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/referenceManager?characterEncoding=utf8
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    database: MYSQL
    thymeleaf:
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
  http:
    multipart:
      max-request-size: 1000Mb


  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
      static-path-pattern: /static/**

custom:
  attachment-path: /Users/zhoujiacheng/Documents/attachment/